apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-repro

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.5.6
  - namespace.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: argocd-server
    path: argocd-server-patch.yaml

# images:
#   - name: argoproj/argocd
#     newName: PRIVATE_IMAGE_REGISTRY/argocd-server
#     newTag: 1.5.6
